<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__zipcode</name>
   <tag></tag>
   <elementGuidId>5fd7c3ae-97c0-4387-8d59-21c9641c405b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#zipcode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='zipcode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#zipcode</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>578f5fea-368e-48a2-830b-9a17cd0fdb01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7e4b3887-dbbe-4f81-9709-1fc83c0a99a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa</name>
      <type>Main</type>
      <value>zipcode</value>
      <webElementGuid>704cef96-8f40-4aab-89d0-a0c9cab73518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>58afc75b-f8fb-4f69-89ed-224ce676b437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zipcode</value>
      <webElementGuid>1afc2c58-006c-424d-8798-3b64ec7b9aee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zipcode</value>
      <webElementGuid>b57c3cfc-0b4c-4479-8c91-3ddd13b0ec08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zipcode&quot;)</value>
      <webElementGuid>948ae2c8-74ff-476f-ad85-fb14b5be9a4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='zipcode']</value>
      <webElementGuid>39abe057-8612-41d4-95f6-7da95ceb7b9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='form']/div/div/div/div/form/p[9]/input</value>
      <webElementGuid>13b3862e-93d5-4887-bf81-ad4a0dc8240b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[9]/input</value>
      <webElementGuid>c1205464-e38b-47bc-9c0f-5dd69ebb245e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'zipcode' and @id = 'zipcode']</value>
      <webElementGuid>b2103f4a-94c8-4db7-b135-e4b5e6db4874</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
