<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Expiration_expiry_year</name>
   <tag></tag>
   <elementGuidId>8062d6aa-94f4-4c69-8535-410f5c442b2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;expiry_year&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='expiry_year']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;YYYY&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>415fecb3-959a-4470-8a7b-088784a72d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>expiry_year</value>
      <webElementGuid>25461168-e9eb-41a6-9fad-fb1528a3ae51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa</name>
      <type>Main</type>
      <value>expiry-year</value>
      <webElementGuid>9d2e8491-15a6-4d8f-af8e-af06d380c957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control card-expiry-year</value>
      <webElementGuid>daeab730-66cf-412d-962a-b7a48d0af04e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>YYYY</value>
      <webElementGuid>27ba588c-80dc-43ec-93f3-1f2814daf05e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1652ceb5-217d-43f8-9cb9-e3c055900b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-form&quot;)/div[@class=&quot;form-row&quot;]/div[@class=&quot;col-sm-4 form-group expiration&quot;]/input[@class=&quot;form-control card-expiry-year&quot;]</value>
      <webElementGuid>53636d74-d3fd-4b09-b1c9-7888a08b7ad9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='expiry_year']</value>
      <webElementGuid>e142df36-5fd8-4317-b00c-159dcbe98779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='payment-form']/div[3]/div[3]/input</value>
      <webElementGuid>83faaa94-5e37-42a2-afe2-23fc1a828550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>00591fc5-bbc8-4fdf-8315-39114d035afd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'expiry_year' and @placeholder = 'YYYY' and @type = 'text']</value>
      <webElementGuid>d59a5ef7-3ed3-4770-bb14-1134bf0a3f5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
